//artworks-----------------------------------------------
export const favouriteArtworks = [
    "3 RWU 23.png",
    "2 malady2.jpg",
    "sleeper medis. finish perfect.png",
    "concept artt1.png",
    "4 woody - Kopie.jpg",
    "TESS 1.png",
    "dwarf 1.png",
    "broken face 9.1.png",
    "scolar.png",
    "hand3.png",
    "thick leg 7.7 1.png",
    "medis update 1.png",
    //"new logo 4.png",

];



export const allArtworks = [
    "Ester.png",
    "queela Kopie 4.png",
    "Evelius dark.png",
    "brush girls 4.png",
    "3 RWU 23.png",
    "pirate girl 2.png",
    "TESS 1.png",
    "sleeper medis. finish perfect.png",
    "broken face 9.1.png",
    "scolar.png",
    "dwarf 1.png",
    "broken face 5.png",
    "thick leg 7.7 1.png",
    "medis update 1.png",
    "new logo 4.png",
    "faces scared.png",
    "ci 2.png",
    "drag.png",
    "elf2.png",
    "copper knight.png",
    "city girl 1.png",
    "space ship.png",
    "faces try11.png",
    "Illustrtfugonfd.png",
    "hand test.png",
    "stuff try2.png",
    "item seller.png",
    "cami portrait2.png",
    "portrait flow.png",
    "face hisabik.png",
    "animals2.png",
    "robooot.png",
    "Illustrtfugon.png",
    "pose 3.png",
    "maiden.png",
    "Fit4.png",
    "cat.png",
    "hand3.png",
    "concept artt1.png",
    "fey.png",
    "hand stange.png",
    "taxas.png",
    "anor londo.png",
    "sitlww.png",
    "newie.png",
    "soft style.png",
    "badey.png",
    "nugt mm - Kopie (2).png",
    "2 malady2.jpg",
    "stuff try.jpg",
    "4 woody - Kopie.jpg",
    "sleeper medis. finish suss.png",
    "ma andro final corrected.png",
    "mh char Ko.png",
    "ägypt.png",
    "jojo 2.png",
    "randm.png",
    "peach saveb.png",
    "haus.png",
    "asoka.png",
    "giant godness - Kopie.png",
    "bergg.png",
    "bergg - Kopie.png",
    "myselff.png",
    "QZ 2 Kopie.png",
    "payaa Kopie.jpg",
    "awakeeo.png",
    "andro2 - Kopie.png",
    "style medica2 Kopie.png",
    "bendi Kopie 2.png",
    "nixe better Kopie.png",
    "medusa better Kopie.png",
    "traffic lights Kopie.png",
    "black tear Kopie.png",
    "goath2.png",
    "bend Ko Kopie.png",
    "showman Kopie.png",
    "troopers1 Kopie.png",
    "me Kopie.png",
    "green2 Kopie.png",
    "comission 1 Kopie.png",
    "nun final 1.png",
    "artoriass.png",
    "connor,real Kopie.png",
    "kegy.png",
    "robo.png",
    "pyroo Kopie.png",
    "nice2 Kopie 2.png",
    "tears Kopie.png",
    "birdhouse big Kopie.png",
    "tammy Kopie 4.png",
    "appf2 Kopie.png",
    "ann Kopie.png",
    "laura Kopie.png",
    "hgf Kopie.png",
    "cornibus1 Kopie.png",
    "yasou.png",
    "witch Kopie.png",
    "sketch w.e.1.2 Kopie.png",
    "mar-splatoon Kopie 2.jpg",
    "Kida.. Kopie.jpg",
    "MM FK Kopie.jpg",
    "solair 1.jpg",
    "Najka like Kopie.jpg",
    "MIMI.png",
    "karla 2 Kopie.jpg",
    "Karla 1 Kopie.jpg",
    "Ms. Lin Kopie.jpg",
    "Dancer finish Kopie.jpg",
    "hand 1.1 Kopie.jpg",
    "dragonslayer armor Kopie.png",
    "high lord wolnir Kopie.png",
    "crystal saga Kopie.png",
    "legion of the abyss Kopie.png",
    "myst Kopie.jpg",
    "emely Kopie.jpg",
    "logo my Kopie.png",
    "tracer fertig 0.2 Kopie.jpg",
    "3 Kopie.jpg",
    "riven ice Kopie 2.jpg",
    "u new 1 Kopie.png",
    "jesustoaster Kopie.png",
    "sarah 11 K Kopie.jpg",
    "shildkröte Kopie.jpg",
    "u new .1.5 Kopie.jpg",
    "firekeeper 2.6 fertig Kopie.jpg",
    "the magic tacoranger 1.2 fertig Kopie.jpg",
    "Sarah 10.4 fertig Kopie.jpg",
    "Amilia 4 fertig Kopie.jpg",
    "Lena .1.5.2 fertig Kopie.jpg",
    "Riven Scann 13.2 fertig Kopie.jpg",
    "Wolf 2 Kopie.jpg",
    "Clara 1.7.2.2 fertig Kopie.jpg"
];